name: Build and release project

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish
        run: dotnet publish ./DroneController/DroneController.csproj -c Release --self-contained true -p:PublishSingleFile=true -o ./out

      - name: Create release Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release Build
          files: ./out/*
